import { hashSeed, mulberry32, shuffle } from '@/lib/seeded'
import { famousLineups as rawLineups } from './lineups'
import enrichment from './enrichment.json'
import type { Famous11sLineup, LineupDifficulty, LineupKind } from './types'

export type {
  Famous11sLineup,
  LineupSlot,
  ManagerSlot,
  LineupKind,
  LineupDifficulty,
} from './types'

/**
 * Curated bank with portraits merged in. `enrichment.json` is generated by
 * `npm run famous11s:verify` - never hand-edited - keeping lineups.ts authoring
 * clean. Missing enrichment just means no image (position box renders instead).
 */
const enrichmentMap = enrichment as Record<string, { playerId?: string; image?: string }>

export const famousLineups: Famous11sLineup[] = rawLineups.map((lineup) => ({
  ...lineup,
  slots: lineup.slots.map((slot) => {
    const key = `${lineup.id}#${slot.slotId}`
    const extra = enrichmentMap[key]
    return extra
      ? { ...slot, playerId: slot.playerId ?? extra.playerId, image: slot.image ?? extra.image }
      : slot
  }),
  manager: lineup.manager
    ? (() => {
        const key = `${lineup.id}#manager`
        const extra = enrichmentMap[key]
        return extra
          ? {
              ...lineup.manager,
              playerId: lineup.manager.playerId ?? extra.playerId,
              image: lineup.manager.image ?? extra.image,
            }
          : lineup.manager
      })()
    : undefined,
}))

export function getLineupById(id: string): Famous11sLineup | undefined {
  return famousLineups.find((l) => l.id === id)
}

export function getLineupsByKind(kind: LineupKind): Famous11sLineup[] {
  return famousLineups.filter((l) => l.kind === kind)
}

export interface SelectLineupOptions {
  kind?: LineupKind | 'all'
  difficulty?: LineupDifficulty | 'mixed'
  excludeIds?: string[]
}

/**
 * Deterministically pick `count` lineups for a session. Same seed + filters →
 * same set (so a puzzle is stable/shareable).
 */
export function selectLineups(
  seed: string,
  count: number,
  opts?: SelectLineupOptions,
): Famous11sLineup[] {
  const kind = opts?.kind
  const difficulty = opts?.difficulty
  const excluded = new Set(opts?.excludeIds ?? [])

  const pool = famousLineups.filter((l) => {
    if (excluded.has(l.id)) return false
    if (kind && kind !== 'all' && l.kind !== kind) return false
    if (difficulty && difficulty !== 'mixed' && l.difficulty !== difficulty) return false
    return true
  })

  const rand = mulberry32(hashSeed(seed))
  return shuffle(pool, rand).slice(0, count)
}

/** Total players (slots) in a lineup - 11 plus 1 for manager if present. */
export function lineupTarget(lineup: Famous11sLineup, includeManager: boolean): number {
  return lineup.slots.length + (includeManager && lineup.manager ? 1 : 0)
}
