// Auto-generated by scripts/fetchWikiCareerStats.ts — do not edit by hand.
// Club career totals from English Wikipedia for players whose Transfermarkt
// stats are missing or a stub (under 50 appearances).

export const wikiCareerStats: Record<
  string,
  { appearances: number; goals: number; via: 'table' | 'infobox'; page: string }
> = {
  "4": {
    "appearances": 694,
    "goals": 226,
    "via": "table",
    "page": "Youri Djorkaeff"
  },
  "19": {
    "appearances": 399,
    "goals": 60,
    "via": "infobox",
    "page": "Marco Reich"
  },
  "26": {
    "appearances": 525,
    "goals": 0,
    "via": "table",
    "page": "Roman Weidenfeller"
  },
  "56": {
    "appearances": 516,
    "goals": 212,
    "via": "table",
    "page": "Oliver Bierhoff"
  },
  "67": {
    "appearances": 173,
    "goals": 33,
    "via": "infobox",
    "page": "Markus Daun"
  },
  "70": {
    "appearances": 513,
    "goals": 53,
    "via": "table",
    "page": "Emerson (footballer, born 1976)"
  },
  "75": {
    "appearances": 493,
    "goals": 15,
    "via": "table",
    "page": "Robert Kovač"
  },
  "76": {
    "appearances": 394,
    "goals": 9,
    "via": "infobox",
    "page": "Diego Placente"
  },
  "77": {
    "appearances": 675,
    "goals": 49,
    "via": "table",
    "page": "Lúcio"
  },
  "82": {
    "appearances": 427,
    "goals": 15,
    "via": "table",
    "page": "Jens Nowotny"
  },
  "89": {
    "appearances": 840,
    "goals": 83,
    "via": "table",
    "page": "Zé Roberto"
  },
  "90": {
    "appearances": 543,
    "goals": 73,
    "via": "table",
    "page": "Bernd Schneider (footballer)"
  },
  "119": {
    "appearances": 635,
    "goals": 48,
    "via": "table",
    "page": "Jürgen Kohler"
  },
  "122": {
    "appearances": 787,
    "goals": 2,
    "via": "table",
    "page": "Jens Lehmann"
  },
  "124": {
    "appearances": 627,
    "goals": 170,
    "via": "table",
    "page": "Andreas Möller"
  },
  "192": {
    "appearances": 355,
    "goals": 18,
    "via": "infobox",
    "page": "Markus Babbel"
  },
  "197": {
    "appearances": 550,
    "goals": 111,
    "via": "table",
    "page": "Stefan Effenberg"
  },
  "201": {
    "appearances": 261,
    "goals": 13,
    "via": "table",
    "page": "Owen Hargreaves"
  },
  "208": {
    "appearances": 353,
    "goals": 11,
    "via": "table",
    "page": "Samuel Kuffour"
  },
  "210": {
    "appearances": 601,
    "goals": 36,
    "via": "table",
    "page": "Bixente Lizarazu"
  },
  "215": {
    "appearances": 932,
    "goals": 254,
    "via": "table",
    "page": "Roque Santa Cruz"
  },
  "217": {
    "appearances": 530,
    "goals": 129,
    "via": "table",
    "page": "Mehmet Scholl"
  },
  "286": {
    "appearances": 492,
    "goals": 155,
    "via": "table",
    "page": "Marc Wilmots"
  },
  "514": {
    "appearances": 548,
    "goals": 249,
    "via": "table",
    "page": "Jan Åge Fjørtoft"
  },
  "528": {
    "appearances": 649,
    "goals": 84,
    "via": "table",
    "page": "Torsten Frings"
  },
  "532": {
    "appearances": 787,
    "goals": 317,
    "via": "table",
    "page": "Claudio Pizarro"
  },
  "553": {
    "appearances": 685,
    "goals": 110,
    "via": "table",
    "page": "Thomas Häßler"
  },
  "916": {
    "appearances": 396,
    "goals": 68,
    "via": "table",
    "page": "Christian Ziege"
  },
  "919": {
    "appearances": 538,
    "goals": 27,
    "via": "table",
    "page": "Dietmar Hamann"
  },
  "1075": {
    "appearances": 400,
    "goals": 115,
    "via": "table",
    "page": "Andriy Voronin"
  },
  "1157": {
    "appearances": 586,
    "goals": 245,
    "via": "table",
    "page": "Jan Koller"
  },
  "1320": {
    "appearances": 302,
    "goals": 0,
    "via": "table",
    "page": "Tomasz Kuszczak"
  },
  "1403": {
    "appearances": 228,
    "goals": 6,
    "via": "table",
    "page": "Taribo West"
  },
  "1419": {
    "appearances": 501,
    "goals": 18,
    "via": "table",
    "page": "Rigobert Song"
  },
  "1519": {
    "appearances": 397,
    "goals": 97,
    "via": "table",
    "page": "Angelos Charisteas"
  },
  "2989": {
    "appearances": 735,
    "goals": 280,
    "via": "table",
    "page": "Paolo Guerrero"
  },
  "3081": {
    "appearances": 550,
    "goals": 210,
    "via": "table",
    "page": "Tore André Flo"
  },
  "3088": {
    "appearances": 411,
    "goals": 8,
    "via": "table",
    "page": "Lucas Radebe"
  },
  "3091": {
    "appearances": 422,
    "goals": 153,
    "via": "table",
    "page": "Benni McCarthy"
  },
  "3095": {
    "appearances": 257,
    "goals": 39,
    "via": "table",
    "page": "Jesper Blomqvist"
  },
  "3098": {
    "appearances": 636,
    "goals": 26,
    "via": "table",
    "page": "Olof Mellberg"
  },
  "3113": {
    "appearances": 712,
    "goals": 137,
    "via": "table",
    "page": "Laurent Blanc"
  },
  "3115": {
    "appearances": 250,
    "goals": 45,
    "via": "infobox",
    "page": "David Bellion"
  },
  "3131": {
    "appearances": 660,
    "goals": 282,
    "via": "table",
    "page": "Kevin Phillips (English footballer)"
  },
  "3133": {
    "appearances": 542,
    "goals": 124,
    "via": "table",
    "page": "Nwankwo Kanu"
  },
  "3134": {
    "appearances": 520,
    "goals": 89,
    "via": "table",
    "page": "Freddie Ljungberg"
  },
  "3141": {
    "appearances": 959,
    "goals": 0,
    "via": "table",
    "page": "David Seaman"
  },
  "3142": {
    "appearances": 786,
    "goals": 164,
    "via": "table",
    "page": "Emile Heskey"
  },
  "3146": {
    "appearances": 636,
    "goals": 0,
    "via": "table",
    "page": "Shay Given"
  },
  "3156": {
    "appearances": 608,
    "goals": 36,
    "via": "table",
    "page": "William Gallas"
  },
  "3173": {
    "appearances": 551,
    "goals": 69,
    "via": "table",
    "page": "Boudewijn Zenden"
  },
  "3175": {
    "appearances": 591,
    "goals": 249,
    "via": "table",
    "page": "Jimmy Floyd Hasselbaink"
  },
  "3184": {
    "appearances": 757,
    "goals": 14,
    "via": "table",
    "page": "Martin Keown"
  },
  "3191": {
    "appearances": 585,
    "goals": 69,
    "via": "table",
    "page": "Giovanni van Bronckhorst"
  },
  "3195": {
    "appearances": 448,
    "goals": 27,
    "via": "table",
    "page": "Jermaine Pennant"
  },
  "3198": {
    "appearances": 646,
    "goals": 29,
    "via": "table",
    "page": "Sol Campbell"
  },
  "3208": {
    "appearances": 542,
    "goals": 32,
    "via": "table",
    "page": "Ray Parlour"
  },
  "3209": {
    "appearances": 389,
    "goals": 0,
    "via": "table",
    "page": "Jerzy Dudek"
  },
  "3210": {
    "appearances": 513,
    "goals": 4,
    "via": "table",
    "page": "Stéphane Henchoz"
  },
  "3216": {
    "appearances": 556,
    "goals": 177,
    "via": "table",
    "page": "Milan Baroš"
  },
  "3217": {
    "appearances": 71,
    "goals": 7,
    "via": "table",
    "page": "Vladimír Šmicer"
  },
  "3218": {
    "appearances": 460,
    "goals": 83,
    "via": "table",
    "page": "Patrik Berger"
  },
  "3219": {
    "appearances": 321,
    "goals": 0,
    "via": "table",
    "page": "Chris Kirkland"
  },
  "3220": {
    "appearances": 754,
    "goals": 65,
    "via": "table",
    "page": "John Arne Riise"
  },
  "3221": {
    "appearances": 769,
    "goals": 121,
    "via": "table",
    "page": "Danny Murphy (footballer, born 1977)"
  },
  "3224": {
    "appearances": 391,
    "goals": 11,
    "via": "table",
    "page": "Jonathan Woodgate"
  },
  "3225": {
    "appearances": 590,
    "goals": 259,
    "via": "table",
    "page": "Robbie Fowler"
  },
  "3226": {
    "appearances": 671,
    "goals": 210,
    "via": "table",
    "page": "Nicolas Anelka"
  },
  "3237": {
    "appearances": 362,
    "goals": 62,
    "via": "infobox",
    "page": "Christophe Dugarry"
  },
  "3241": {
    "appearances": 516,
    "goals": 124,
    "via": "table",
    "page": "Harry Kewell"
  },
  "3248": {
    "appearances": 609,
    "goals": 73,
    "via": "infobox",
    "page": "Paul Ince"
  },
  "3274": {
    "appearances": 384,
    "goals": 21,
    "via": "infobox",
    "page": "Iván Campo"
  },
  "3289": {
    "appearances": 598,
    "goals": 0,
    "via": "table",
    "page": "Fabien Barthez"
  },
  "3291": {
    "appearances": 834,
    "goals": 68,
    "via": "table",
    "page": "Gareth Barry"
  },
  "3297": {
    "appearances": 549,
    "goals": 170,
    "via": "table",
    "page": "Craig Bellamy"
  },
  "3308": {
    "appearances": 553,
    "goals": 19,
    "via": "table",
    "page": "Stephen Warnock"
  },
  "3333": {
    "appearances": 903,
    "goals": 86,
    "via": "table",
    "page": "James Milner"
  },
  "3357": {
    "appearances": 765,
    "goals": 0,
    "via": "table",
    "page": "Mark Schwarzer"
  },
  "3360": {
    "appearances": 323,
    "goals": 14,
    "via": "table",
    "page": "Ledley King"
  },
  "3365": {
    "appearances": 431,
    "goals": 63,
    "via": "table",
    "page": "Kléberson"
  },
  "3374": {
    "appearances": 397,
    "goals": 34,
    "via": "table",
    "page": "Geremi"
  },
  "3390": {
    "appearances": 521,
    "goals": 40,
    "via": "table",
    "page": "Demetrio Albertini"
  },
  "3392": {
    "appearances": 926,
    "goals": 361,
    "via": "table",
    "page": "Teddy Sheringham"
  },
  "3393": {
    "appearances": 542,
    "goals": 15,
    "via": "table",
    "page": "Mikaël Silvestre"
  },
  "3394": {
    "appearances": 529,
    "goals": 282,
    "via": "table",
    "page": "Ole Gunnar Solskjær"
  },
  "3403": {
    "appearances": 602,
    "goals": 7,
    "via": "table",
    "page": "Gary Neville"
  },
  "3404": {
    "appearances": 689,
    "goals": 13,
    "via": "table",
    "page": "Phil Neville"
  },
  "3405": {
    "appearances": 470,
    "goals": 8,
    "via": "table",
    "page": "Wes Brown"
  },
  "3411": {
    "appearances": 566,
    "goals": 86,
    "via": "table",
    "page": "Pablo Aimar"
  },
  "3415": {
    "appearances": 458,
    "goals": 248,
    "via": "table",
    "page": "Marcelo Salas"
  },
  "3420": {
    "appearances": 414,
    "goals": 98,
    "via": "infobox",
    "page": "Karel Poborský"
  },
  "3424": {
    "appearances": 395,
    "goals": 46,
    "via": "table",
    "page": "Jamie Redknapp"
  },
  "3430": {
    "appearances": 538,
    "goals": 27,
    "via": "table",
    "page": "Kakha Kaladze"
  },
  "3459": {
    "appearances": 841,
    "goals": 135,
    "via": "table",
    "page": "Gary Speed"
  },
  "3460": {
    "appearances": 656,
    "goals": 114,
    "via": "table",
    "page": "Nolberto Solano"
  },
  "3470": {
    "appearances": 753,
    "goals": 49,
    "via": "table",
    "page": "Sami Hyypiä"
  },
  "3476": {
    "appearances": 668,
    "goals": 1,
    "via": "table",
    "page": "Brad Friedel"
  },
  "3478": {
    "appearances": 566,
    "goals": 202,
    "via": "table",
    "page": "Steffen Iversen"
  },
  "3501": {
    "appearances": 547,
    "goals": 262,
    "via": "infobox",
    "page": "Stéphane Chapuisat"
  },
  "3505": {
    "appearances": 449,
    "goals": 103,
    "via": "table",
    "page": "Juninho Paulista"
  },
  "3513": {
    "appearances": 542,
    "goals": 106,
    "via": "table",
    "page": "Marc Overmars"
  },
  "3515": {
    "appearances": 703,
    "goals": 99,
    "via": "table",
    "page": "Mark van Bommel"
  },
  "3518": {
    "appearances": 701,
    "goals": 66,
    "via": "table",
    "page": "Frank de Boer"
  },
  "3519": {
    "appearances": 622,
    "goals": 140,
    "via": "table",
    "page": "Ronald de Boer"
  },
  "3520": {
    "appearances": 638,
    "goals": 377,
    "via": "table",
    "page": "Pierre van Hooijdonk"
  },
  "3526": {
    "appearances": 615,
    "goals": 265,
    "via": "table",
    "page": "Giuseppe Signori"
  },
  "3538": {
    "appearances": 244,
    "goals": 13,
    "via": "infobox",
    "page": "David May (footballer)"
  },
  "3540": {
    "appearances": 684,
    "goals": 20,
    "via": "table",
    "page": "John O'Shea"
  },
  "3541": {
    "appearances": 173,
    "goals": 13,
    "via": "infobox",
    "page": "Quinton Fortune"
  },
  "3543": {
    "appearances": 441,
    "goals": 30,
    "via": "infobox",
    "page": "Nicky Butt"
  },
  "3547": {
    "appearances": 481,
    "goals": 32,
    "via": "table",
    "page": "Darren Fletcher"
  },
  "3548": {
    "appearances": 337,
    "goals": 35,
    "via": "table",
    "page": "Kieran Richardson"
  },
  "3570": {
    "appearances": 492,
    "goals": 173,
    "via": "table",
    "page": "John Carew"
  },
  "3578": {
    "appearances": 375,
    "goals": 32,
    "via": "table",
    "page": "Ronny Johnsen"
  },
  "3597": {
    "appearances": 737,
    "goals": 4,
    "via": "table",
    "page": "Jamie Carragher"
  },
  "3598": {
    "appearances": 325,
    "goals": 4,
    "via": "table",
    "page": "Djimi Traoré"
  },
  "3600": {
    "appearances": 271,
    "goals": 4,
    "via": "table",
    "page": "Salif Diao"
  },
  "3601": {
    "appearances": 377,
    "goals": 28,
    "via": "table",
    "page": "Igor Bišćan"
  },
  "3602": {
    "appearances": 296,
    "goals": 48,
    "via": "table",
    "page": "Bruno Cheyrou"
  },
  "3604": {
    "appearances": 510,
    "goals": 75,
    "via": "table",
    "page": "El Hadji Diouf"
  },
  "3644": {
    "appearances": 473,
    "goals": 1,
    "via": "table",
    "page": "Raimond van der Gouw"
  },
  "3645": {
    "appearances": 523,
    "goals": 215,
    "via": "table",
    "page": "Les Ferdinand"
  },
  "3699": {
    "appearances": 670,
    "goals": 149,
    "via": "table",
    "page": "Paolo Di Canio"
  },
  "3742": {
    "appearances": 575,
    "goals": 97,
    "via": "table",
    "page": "Andrei Kanchelskis"
  },
  "3768": {
    "appearances": 605,
    "goals": 72,
    "via": "table",
    "page": "Alan Smith (footballer, born 1980)"
  },
  "3823": {
    "appearances": 429,
    "goals": 10,
    "via": "table",
    "page": "Henning Berg"
  },
  "3830": {
    "appearances": 468,
    "goals": 110,
    "via": "table",
    "page": "Paul Gascoigne"
  },
  "3839": {
    "appearances": 557,
    "goals": 29,
    "via": "table",
    "page": "Steve Staunton"
  },
  "3865": {
    "appearances": 565,
    "goals": 29,
    "via": "table",
    "page": "Jonathan Greening"
  },
  "3876": {
    "appearances": 679,
    "goals": 94,
    "via": "table",
    "page": "Joe Cole"
  },
  "3878": {
    "appearances": 706,
    "goals": 34,
    "via": "table",
    "page": "Michael Carrick"
  },
  "3881": {
    "appearances": 460,
    "goals": 17,
    "via": "table",
    "page": "Glen Johnson"
  },
  "3920": {
    "appearances": 248,
    "goals": 44,
    "via": "infobox",
    "page": "Bernard Diomède"
  },
  "3966": {
    "appearances": 610,
    "goals": 271,
    "via": "table",
    "page": "Djibril Cissé"
  },
  "3980": {
    "appearances": 566,
    "goals": 80,
    "via": "table",
    "page": "Steve McManaman"
  },
  "3994": {
    "appearances": 638,
    "goals": 315,
    "via": "table",
    "page": "Roy Makaay"
  },
  "4015": {
    "appearances": 492,
    "goals": 159,
    "via": "table",
    "page": "Louis Saha"
  },
  "4038": {
    "appearances": 631,
    "goals": 19,
    "via": "table",
    "page": "Steve Finnan"
  },
  "4063": {
    "appearances": 722,
    "goals": 63,
    "via": "table",
    "page": "Stewart Downing"
  },
  "4072": {
    "appearances": 735,
    "goals": 205,
    "via": "table",
    "page": "Peter Crouch"
  },
  "4126": {
    "appearances": 344,
    "goals": 6,
    "via": "table",
    "page": "Stephen Wright (English footballer)"
  },
  "4147": {
    "appearances": 597,
    "goals": 126,
    "via": "table",
    "page": "Ariel Ortega"
  },
  "4151": {
    "appearances": 435,
    "goals": 23,
    "via": "infobox",
    "page": "Aldair"
  },
  "4169": {
    "appearances": 578,
    "goals": 236,
    "via": "table",
    "page": "Jon Dahl Tomasson"
  },
  "4182": {
    "appearances": 809,
    "goals": 25,
    "via": "table",
    "page": "Claude Makélélé"
  },
  "4192": {
    "appearances": 538,
    "goals": 171,
    "via": "table",
    "page": "Rafael van der Vaart"
  },
  "4216": {
    "appearances": 402,
    "goals": 93,
    "via": "table",
    "page": "Florent Sinama Pongolle"
  },
  "4226": {
    "appearances": 626,
    "goals": 247,
    "via": "table",
    "page": "Fabrizio Ravanelli"
  },
  "4280": {
    "appearances": 900,
    "goals": 43,
    "via": "table",
    "page": "Denis Irwin"
  },
  "4314": {
    "appearances": 486,
    "goals": 27,
    "via": "table",
    "page": "Cristian Chivu"
  },
  "4357": {
    "appearances": 665,
    "goals": 367,
    "via": "table",
    "page": "Klaas-Jan Huntelaar"
  },
  "4549": {
    "appearances": 386,
    "goals": 14,
    "via": "table",
    "page": "Jan Kromkamp"
  },
  "4592": {
    "appearances": 434,
    "goals": 58,
    "via": "table",
    "page": "Park Ji-sung"
  },
  "4672": {
    "appearances": 496,
    "goals": 29,
    "via": "table",
    "page": "Nigel de Jong"
  },
  "4977": {
    "appearances": 437,
    "goals": 213,
    "via": "infobox",
    "page": "Alexander Frei"
  },
  "5198": {
    "appearances": 774,
    "goals": 151,
    "via": "table",
    "page": "Phillip Cocu"
  },
  "5299": {
    "appearances": 755,
    "goals": 171,
    "via": "table",
    "page": "Ludovic Giuly"
  },
  "5314": {
    "appearances": 480,
    "goals": 89,
    "via": "infobox",
    "page": "Frank Leboeuf"
  },
  "5352": {
    "appearances": 432,
    "goals": 29,
    "via": "table",
    "page": "Mahamadou Diarra"
  },
  "5461": {
    "appearances": 706,
    "goals": 119,
    "via": "table",
    "page": "Florent Malouda"
  },
  "5486": {
    "appearances": 653,
    "goals": 78,
    "via": "table",
    "page": "Seydou Keita"
  },
  "5509": {
    "appearances": 317,
    "goals": 11,
    "via": "infobox",
    "page": "Eric Djemba-Djemba"
  },
  "5555": {
    "appearances": 514,
    "goals": 30,
    "via": "table",
    "page": "Gabriel Heinze"
  },
  "5604": {
    "appearances": 729,
    "goals": 59,
    "via": "table",
    "page": "José Luis Chilavert"
  },
  "5759": {
    "appearances": 512,
    "goals": 46,
    "via": "table",
    "page": "Antonio Conte"
  },
  "5769": {
    "appearances": 639,
    "goals": 0,
    "via": "table",
    "page": "Francesco Toldo"
  },
  "5778": {
    "appearances": 491,
    "goals": 58,
    "via": "table",
    "page": "Marco Materazzi"
  },
  "5796": {
    "appearances": 528,
    "goals": 150,
    "via": "table",
    "page": "Álvaro Recoba"
  },
  "5800": {
    "appearances": 723,
    "goals": 0,
    "via": "table",
    "page": "Dida (footballer, born 1973)"
  },
  "5813": {
    "appearances": 586,
    "goals": 17,
    "via": "table",
    "page": "Gennaro Gattuso"
  },
  "5821": {
    "appearances": 623,
    "goals": 288,
    "via": "table",
    "page": "Filippo Inzaghi"
  },
  "5831": {
    "appearances": 583,
    "goals": 35,
    "via": "table",
    "page": "Fernando Couto"
  },
  "5834": {
    "appearances": 580,
    "goals": 99,
    "via": "table",
    "page": "Siniša Mihajlović"
  },
  "5841": {
    "appearances": 641,
    "goals": 101,
    "via": "table",
    "page": "Diego Simeone"
  },
  "5855": {
    "appearances": 635,
    "goals": 0,
    "via": "table",
    "page": "Cláudio Taffarel"
  },
  "5879": {
    "appearances": 532,
    "goals": 204,
    "via": "table",
    "page": "Adrian Mutu"
  },
  "5938": {
    "appearances": 641,
    "goals": 39,
    "via": "table",
    "page": "Walter Samuel"
  },
  "5950": {
    "appearances": 524,
    "goals": 28,
    "via": "table",
    "page": "Pep Guardiola"
  },
  "5957": {
    "appearances": 459,
    "goals": 43,
    "via": "table",
    "page": "Alberto Aquilani"
  },
  "5960": {
    "appearances": 383,
    "goals": 192,
    "via": "infobox",
    "page": "Vincenzo Montella"
  },
  "5980": {
    "appearances": 658,
    "goals": 306,
    "via": "table",
    "page": "Luca Toni"
  },
  "6031": {
    "appearances": 686,
    "goals": 300,
    "via": "table",
    "page": "Antonio Di Natale"
  },
  "6069": {
    "appearances": 795,
    "goals": 136,
    "via": "table",
    "page": "Shunsuke Nakamura"
  },
  "6119": {
    "appearances": 402,
    "goals": 16,
    "via": "table",
    "page": "Mohamed Sissoko"
  },
  "6710": {
    "appearances": 518,
    "goals": 34,
    "via": "table",
    "page": "Per Mertesacker"
  },
  "7279": {
    "appearances": 271,
    "goals": 21,
    "via": "infobox",
    "page": "Flávio Conceição"
  },
  "7373": {
    "appearances": 487,
    "goals": 59,
    "via": "table",
    "page": "Albert Riera"
  },
  "7427": {
    "appearances": 651,
    "goals": 244,
    "via": "table",
    "page": "Ivica Olić"
  },
  "7451": {
    "appearances": 539,
    "goals": 74,
    "via": "table",
    "page": "Mikel Arteta"
  },
  "7453": {
    "appearances": 546,
    "goals": 193,
    "via": "table",
    "page": "Chris Sutton"
  },
  "7510": {
    "appearances": 519,
    "goals": 0,
    "via": "table",
    "page": "César Sánchez"
  },
  "7513": {
    "appearances": 722,
    "goals": 135,
    "via": "table",
    "page": "Fernando Hierro"
  },
  "7514": {
    "appearances": 462,
    "goals": 41,
    "via": "table",
    "page": "Iván Helguera"
  },
  "7515": {
    "appearances": 587,
    "goals": 11,
    "via": "table",
    "page": "Míchel Salgado"
  },
  "7516": {
    "appearances": 85,
    "goals": 5,
    "via": "infobox",
    "page": "Óscar Miñambres"
  },
  "7517": {
    "appearances": 279,
    "goals": 9,
    "via": "table",
    "page": "Francisco Pavón"
  },
  "7520": {
    "appearances": 715,
    "goals": 90,
    "via": "table",
    "page": "Esteban Cambiasso"
  },
  "7521": {
    "appearances": 281,
    "goals": 15,
    "via": "infobox",
    "page": "Albert Celades"
  },
  "7527": {
    "appearances": 496,
    "goals": 59,
    "via": "table",
    "page": "Santiago Solari"
  },
  "7530": {
    "appearances": 611,
    "goals": 100,
    "via": "table",
    "page": "Guti"
  },
  "7532": {
    "appearances": 421,
    "goals": 114,
    "via": "table",
    "page": "Javier Portillo (Spanish footballer)"
  },
  "7562": {
    "appearances": 637,
    "goals": 0,
    "via": "table",
    "page": "Santiago Cañizares"
  },
  "7565": {
    "appearances": 609,
    "goals": 19,
    "via": "table",
    "page": "Roberto Ayala"
  },
  "7570": {
    "appearances": 242,
    "goals": 17,
    "via": "infobox",
    "page": "Fábio Aurélio"
  },
  "7589": {
    "appearances": 509,
    "goals": 0,
    "via": "infobox",
    "page": "Víctor Valdés"
  },
  "7603": {
    "appearances": 480,
    "goals": 71,
    "via": "table",
    "page": "Gaizka Mendieta"
  },
  "7611": {
    "appearances": 590,
    "goals": 216,
    "via": "table",
    "page": "Javier Saviola"
  },
  "7660": {
    "appearances": 517,
    "goals": 59,
    "via": "table",
    "page": "Denílson (footballer, born 1977)"
  },
  "7663": {
    "appearances": 913,
    "goals": 115,
    "via": "table",
    "page": "Joaquín (footballer, born 1981)"
  },
  "7825": {
    "appearances": 954,
    "goals": 0,
    "via": "table",
    "page": "Pepe Reina"
  },
  "7858": {
    "appearances": 749,
    "goals": 183,
    "via": "table",
    "page": "Yossi Benayoun"
  },
  "7864": {
    "appearances": 475,
    "goals": 53,
    "via": "infobox",
    "page": "Pedro Munitis"
  },
  "7895": {
    "appearances": 670,
    "goals": 195,
    "via": "table",
    "page": "Maxi Rodríguez"
  },
  "7912": {
    "appearances": 526,
    "goals": 68,
    "via": "table",
    "page": "Sérgio Conceição"
  },
  "7920": {
    "appearances": 587,
    "goals": 140,
    "via": "table",
    "page": "Luis García (footballer, born 1978)"
  },
  "7940": {
    "appearances": 685,
    "goals": 238,
    "via": "table",
    "page": "Ronald Koeman"
  },
  "7976": {
    "appearances": 375,
    "goals": 74,
    "via": "infobox",
    "page": "Sávio (footballer, born 1974)"
  },
  "8013": {
    "appearances": 505,
    "goals": 113,
    "via": "table",
    "page": "Robert Prosinečki"
  },
  "8016": {
    "appearances": 575,
    "goals": 0,
    "via": "table",
    "page": "Vítor Baía"
  },
  "8019": {
    "appearances": 656,
    "goals": 161,
    "via": "table",
    "page": "Simão Sabrosa"
  },
  "8022": {
    "appearances": 799,
    "goals": 224,
    "via": "table",
    "page": "Mark Hughes"
  },
  "8117": {
    "appearances": 872,
    "goals": 0,
    "via": "table",
    "page": "Andoni Zubizarreta"
  },
  "9209": {
    "appearances": 395,
    "goals": 18,
    "via": "infobox",
    "page": "Christian Karembeu"
  },
  "9706": {
    "appearances": 271,
    "goals": 20,
    "via": "infobox",
    "page": "Sotirios Kyrgiakos"
  },
  "9822": {
    "appearances": 449,
    "goals": 64,
    "via": "table",
    "page": "Maniche"
  },
  "9828": {
    "appearances": 610,
    "goals": 24,
    "via": "table",
    "page": "Ricardo Carvalho"
  },
  "9867": {
    "appearances": 621,
    "goals": 35,
    "via": "table",
    "page": "Theodoros Zagorakis"
  },
  "10032": {
    "appearances": 868,
    "goals": 154,
    "via": "table",
    "page": "Gary McAllister"
  },
  "10055": {
    "appearances": 694,
    "goals": 3,
    "via": "table",
    "page": "Alessandro Costacurta"
  },
  "10201": {
    "appearances": 338,
    "goals": 105,
    "via": "infobox",
    "page": "Rivellino"
  },
  "10367": {
    "appearances": 433,
    "goals": 125,
    "via": "table",
    "page": "Claudio Caniggia"
  },
  "12282": {
    "appearances": 612,
    "goals": 22,
    "via": "table",
    "page": "Daley Blind"
  },
  "13572": {
    "appearances": 547,
    "goals": 0,
    "via": "table",
    "page": "Ben Foster (footballer)"
  },
  "13775": {
    "appearances": 673,
    "goals": 318,
    "via": "table",
    "page": "Rudi Völler"
  },
  "13804": {
    "appearances": 406,
    "goals": 25,
    "via": "table",
    "page": "Rune Bratseth"
  },
  "14086": {
    "appearances": 763,
    "goals": 87,
    "via": "table",
    "page": "Ashley Young"
  },
  "14942": {
    "appearances": 648,
    "goals": 57,
    "via": "table",
    "page": "Darijo Srna"
  },
  "15185": {
    "appearances": 708,
    "goals": 227,
    "via": "table",
    "page": "Lukas Podolski"
  },
  "15773": {
    "appearances": 403,
    "goals": 14,
    "via": "table",
    "page": "Phil Bardsley"
  },
  "15799": {
    "appearances": 776,
    "goals": 143,
    "via": "table",
    "page": "Santi Cazorla"
  },
  "16036": {
    "appearances": 674,
    "goals": 259,
    "via": "table",
    "page": "Gianluca Vialli"
  },
  "16056": {
    "appearances": 623,
    "goals": 80,
    "via": "table",
    "page": "Andreas Brehme"
  },
  "16135": {
    "appearances": 650,
    "goals": 134,
    "via": "table",
    "page": "Ryan Babel"
  },
  "16635": {
    "appearances": 581,
    "goals": 19,
    "via": "table",
    "page": "Juanfran (footballer, born 1985)"
  },
  "16911": {
    "appearances": 817,
    "goals": 0,
    "via": "table",
    "page": "Kasper Schmeichel"
  },
  "17121": {
    "appearances": 647,
    "goals": 606,
    "via": "infobox",
    "page": "Pelé"
  },
  "17965": {
    "appearances": 870,
    "goals": 0,
    "via": "table",
    "page": "Hugo Lloris"
  },
  "18301": {
    "appearances": 604,
    "goals": 36,
    "via": "table",
    "page": "Maicon (footballer, born 1981)"
  },
  "18935": {
    "appearances": 519,
    "goals": 73,
    "via": "table",
    "page": "Samir Nasri"
  },
  "18944": {
    "appearances": 667,
    "goals": 57,
    "via": "table",
    "page": "Gerard Piqué"
  },
  "19368": {
    "appearances": 594,
    "goals": 67,
    "via": "table",
    "page": "Mousa Dembélé (Belgian footballer)"
  },
  "20007": {
    "appearances": 594,
    "goals": 24,
    "via": "table",
    "page": "Pablo Zabaleta"
  },
  "21369": {
    "appearances": 533,
    "goals": 90,
    "via": "table",
    "page": "Arda Turan"
  },
  "21654": {
    "appearances": 267,
    "goals": 113,
    "via": "table",
    "page": "Martin Dahlin"
  },
  "21750": {
    "appearances": 274,
    "goals": 62,
    "via": "infobox",
    "page": "Mark González"
  },
  "21863": {
    "appearances": 343,
    "goals": 11,
    "via": "infobox",
    "page": "Andrea Dossena"
  },
  "22068": {
    "appearances": 715,
    "goals": 161,
    "via": "table",
    "page": "Franck Ribéry"
  },
  "22412": {
    "appearances": 586,
    "goals": 0,
    "via": "table",
    "page": "Júlio César (football goalkeeper, born 1979)"
  },
  "22832": {
    "appearances": 305,
    "goals": 21,
    "via": "table",
    "page": "Daniel Agger"
  },
  "23102": {
    "appearances": 371,
    "goals": 89,
    "via": "infobox",
    "page": "Riki (footballer, born 1980)"
  },
  "24180": {
    "appearances": 662,
    "goals": 35,
    "via": "table",
    "page": "Martin Škrtel"
  },
  "24474": {
    "appearances": 501,
    "goals": 0,
    "via": "table",
    "page": "Bodo Illgner"
  },
  "24481": {
    "appearances": 534,
    "goals": 176,
    "via": "table",
    "page": "Predrag Mijatović"
  },
  "24635": {
    "appearances": 424,
    "goals": 61,
    "via": "table",
    "page": "Chris Eagles"
  },
  "25553": {
    "appearances": 541,
    "goals": 25,
    "via": "table",
    "page": "Brede Hangeland"
  },
  "26101": {
    "appearances": 243,
    "goals": 8,
    "via": "table",
    "page": "Cicinho"
  },
  "26267": {
    "appearances": 556,
    "goals": 98,
    "via": "table",
    "page": "Fernandinho (footballer, born November 1985)"
  },
  "26485": {
    "appearances": 601,
    "goals": 12,
    "via": "table",
    "page": "Jérôme Boateng"
  },
  "26541": {
    "appearances": 372,
    "goals": 197,
    "via": "table",
    "page": "Bebeto"
  },
  "27486": {
    "appearances": 381,
    "goals": 0,
    "via": "table",
    "page": "Kiko Casilla"
  },
  "27705": {
    "appearances": 423,
    "goals": 103,
    "via": "table",
    "page": "Paulo Futre"
  },
  "28021": {
    "appearances": 730,
    "goals": 0,
    "via": "table",
    "page": "Samir Handanović"
  },
  "28066": {
    "appearances": 595,
    "goals": 187,
    "via": "table",
    "page": "Cuauhtémoc Blanco"
  },
  "28238": {
    "appearances": 504,
    "goals": 32,
    "via": "infobox",
    "page": "Tony Adams"
  },
  "28260": {
    "appearances": 459,
    "goals": 8,
    "via": "table",
    "page": "Álvaro Arbeloa"
  },
  "28261": {
    "appearances": 458,
    "goals": 49,
    "via": "table",
    "page": "José Manuel Jurado"
  },
  "28990": {
    "appearances": 552,
    "goals": 100,
    "via": "table",
    "page": "Charlie Adam"
  },
  "29364": {
    "appearances": 1008,
    "goals": 65,
    "via": "table",
    "page": "João Moutinho"
  },
  "29559": {
    "appearances": 778,
    "goals": 0,
    "via": "table",
    "page": "Guillermo Ochoa"
  },
  "30739": {
    "appearances": 495,
    "goals": 11,
    "via": "table",
    "page": "Mikel John Obi"
  },
  "30767": {
    "appearances": 414,
    "goals": 23,
    "via": "table",
    "page": "Gabriel Paletta"
  },
  "31095": {
    "appearances": 416,
    "goals": 37,
    "via": "table",
    "page": "Nuri Şahin"
  },
  "31645": {
    "appearances": 371,
    "goals": 30,
    "via": "table",
    "page": "Anderson (footballer, born 1988)"
  },
  "33706": {
    "appearances": 638,
    "goals": 130,
    "via": "table",
    "page": "Nani (footballer)"
  },
  "33713": {
    "appearances": 564,
    "goals": 129,
    "via": "table",
    "page": "Theo Walcott"
  },
  "33923": {
    "appearances": 699,
    "goals": 50,
    "via": "table",
    "page": "Blaise Matuidi"
  },
  "34130": {
    "appearances": 380,
    "goals": 0,
    "via": "table",
    "page": "Tom Heaton"
  },
  "34370": {
    "appearances": 674,
    "goals": 0,
    "via": "table",
    "page": "Diego López (Spanish footballer, born 1981)"
  },
  "34572": {
    "appearances": 582,
    "goals": 228,
    "via": "table",
    "page": "Mario Mandžukić"
  },
  "35518": {
    "appearances": 784,
    "goals": 125,
    "via": "table",
    "page": "David Silva"
  },
  "35522": {
    "appearances": 76,
    "goals": 11,
    "via": "table",
    "page": "Rubén de la Red"
  },
  "35571": {
    "appearances": 316,
    "goals": 5,
    "via": "table",
    "page": "José Enrique (footballer, born 1986)"
  },
  "35773": {
    "appearances": 575,
    "goals": 190,
    "via": "table",
    "page": "Carlos Vela"
  },
  "35894": {
    "appearances": 446,
    "goals": 131,
    "via": "table",
    "page": "Dejan Savićević"
  },
  "36350": {
    "appearances": 483,
    "goals": 28,
    "via": "table",
    "page": "Javi García"
  },
  "37442": {
    "appearances": 428,
    "goals": 4,
    "via": "table",
    "page": "Danny Simpson"
  },
  "37579": {
    "appearances": 500,
    "goals": 188,
    "via": "table",
    "page": "Alexandre Pato"
  },
  "37666": {
    "appearances": 818,
    "goals": 128,
    "via": "table",
    "page": "Arturo Vidal"
  },
  "37838": {
    "appearances": 549,
    "goals": 22,
    "via": "table",
    "page": "Dejan Lovren"
  },
  "38593": {
    "appearances": 716,
    "goals": 146,
    "via": "table",
    "page": "Marek Hamšík"
  },
  "38954": {
    "appearances": 388,
    "goals": 12,
    "via": "table",
    "page": "Fernando Gago"
  },
  "39679": {
    "appearances": 579,
    "goals": 117,
    "via": "table",
    "page": "Marouane Fellaini"
  },
  "39983": {
    "appearances": 678,
    "goals": 46,
    "via": "table",
    "page": "Leonardo Bonucci"
  },
  "40204": {
    "appearances": 705,
    "goals": 0,
    "via": "table",
    "page": "Joe Hart"
  },
  "40423": {
    "appearances": 580,
    "goals": 1,
    "via": "table",
    "page": "Claudio Bravo"
  },
  "41242": {
    "appearances": 331,
    "goals": 68,
    "via": "table",
    "page": "David Ngog"
  },
  "41414": {
    "appearances": 640,
    "goals": 25,
    "via": "table",
    "page": "Lucas Leiva"
  },
  "41982": {
    "appearances": 625,
    "goals": 77,
    "via": "table",
    "page": "Radja Nainggolan"
  },
  "42205": {
    "appearances": 807,
    "goals": 0,
    "via": "table",
    "page": "Yann Sommer"
  },
  "42412": {
    "appearances": 538,
    "goals": 23,
    "via": "table",
    "page": "Jonny Evans"
  },
  "42710": {
    "appearances": 635,
    "goals": 42,
    "via": "table",
    "page": "Toby Alderweireld"
  },
  "43261": {
    "appearances": 363,
    "goals": 34,
    "via": "table",
    "page": "Gabriel Obertan"
  },
  "43530": {
    "appearances": 569,
    "goals": 86,
    "via": "table",
    "page": "Adam Lallana"
  },
  "43705": {
    "appearances": 541,
    "goals": 209,
    "via": "table",
    "page": "Matt Le Tissier"
  },
  "43907": {
    "appearances": 826,
    "goals": 360,
    "via": "table",
    "page": "André-Pierre Gignac"
  },
  "44068": {
    "appearances": 700,
    "goals": 148,
    "via": "table",
    "page": "Juan Mata"
  },
  "44069": {
    "appearances": 380,
    "goals": 15,
    "via": "table",
    "page": "Pedro Mosquera"
  },
  "44162": {
    "appearances": 665,
    "goals": 78,
    "via": "table",
    "page": "Miralem Pjanić"
  },
  "44501": {
    "appearances": 663,
    "goals": 52,
    "via": "table",
    "page": "Marcelo (footballer, born 1988)"
  },
  "44779": {
    "appearances": 561,
    "goals": 200,
    "via": "table",
    "page": "Diego Costa"
  },
  "45146": {
    "appearances": 485,
    "goals": 195,
    "via": "table",
    "page": "Mario Balotelli"
  },
  "45305": {
    "appearances": 292,
    "goals": 1,
    "via": "table",
    "page": "Miguel Torres (footballer, born 1986)"
  },
  "45599": {
    "appearances": 345,
    "goals": 11,
    "via": "table",
    "page": "Emiliano Insúa"
  },
  "45861": {
    "appearances": 492,
    "goals": 28,
    "via": "table",
    "page": "Ryan Shawcross"
  },
  "46156": {
    "appearances": 580,
    "goals": 58,
    "via": "table",
    "page": "Aleksandar Kolarov"
  },
  "46180": {
    "appearances": 542,
    "goals": 115,
    "via": "table",
    "page": "Zoran Tošić"
  },
  "46741": {
    "appearances": 793,
    "goals": 47,
    "via": "table",
    "page": "David Luiz"
  },
  "47713": {
    "appearances": 424,
    "goals": 12,
    "via": "table",
    "page": "Mamadou Sakho"
  },
  "48066": {
    "appearances": 479,
    "goals": 116,
    "via": "table",
    "page": "Andy Carroll"
  },
  "49499": {
    "appearances": 735,
    "goals": 159,
    "via": "table",
    "page": "Georginio Wijnaldum"
  },
  "50057": {
    "appearances": 548,
    "goals": 80,
    "via": "table",
    "page": "Aaron Ramsey"
  },
  "50570": {
    "appearances": 560,
    "goals": 161,
    "via": "table",
    "page": "Ezequiel Lavezzi"
  },
  "50935": {
    "appearances": 547,
    "goals": 199,
    "via": "table",
    "page": "Javier Hernández"
  },
  "52312": {
    "appearances": 466,
    "goals": 148,
    "via": "table",
    "page": "Sebastian Giovinco"
  },
  "52769": {
    "appearances": 818,
    "goals": 117,
    "via": "table",
    "page": "Willian (footballer, born 1988)"
  },
  "54906": {
    "appearances": 543,
    "goals": 22,
    "via": "table",
    "page": "Matteo Darmian"
  },
  "55838": {
    "appearances": 380,
    "goals": 40,
    "via": "infobox",
    "page": "René Higuita"
  },
  "56416": {
    "appearances": 831,
    "goals": 274,
    "via": "table",
    "page": "Dries Mertens"
  },
  "56818": {
    "appearances": 518,
    "goals": 25,
    "via": "table",
    "page": "Morgan Schneiderlin"
  },
  "57071": {
    "appearances": 519,
    "goals": 0,
    "via": "table",
    "page": "Péter Gulácsi"
  },
  "59606": {
    "appearances": 437,
    "goals": 14,
    "via": "table",
    "page": "Craig Cathcart"
  },
  "60444": {
    "appearances": 488,
    "goals": 48,
    "via": "table",
    "page": "Thiago Alcântara"
  },
  "61891": {
    "appearances": 347,
    "goals": 8,
    "via": "table",
    "page": "Fabio (footballer, born 1990)"
  },
  "61892": {
    "appearances": 377,
    "goals": 7,
    "via": "table",
    "page": "Rafael (footballer, born 1990)"
  },
  "62049": {
    "appearances": 470,
    "goals": 155,
    "via": "table",
    "page": "Mame Biram Diouf"
  },
  "65230": {
    "appearances": 863,
    "goals": 21,
    "via": "table",
    "page": "Sergio Busquets"
  },
  "65278": {
    "appearances": 902,
    "goals": 215,
    "via": "table",
    "page": "Pedro (footballer, born 1987)"
  },
  "66521": {
    "appearances": 499,
    "goals": 106,
    "via": "table",
    "page": "Keisuke Honda"
  },
  "67063": {
    "appearances": 530,
    "goals": 126,
    "via": "table",
    "page": "Danny Welbeck"
  },
  "68204": {
    "appearances": 738,
    "goals": 201,
    "via": "table",
    "page": "Roberto Mancini"
  },
  "68290": {
    "appearances": 643,
    "goals": 379,
    "via": "table",
    "page": "Neymar"
  },
  "69751": {
    "appearances": 741,
    "goals": 60,
    "via": "table",
    "page": "Jordi Alba"
  },
  "74223": {
    "appearances": 288,
    "goals": 18,
    "via": "table",
    "page": "Jack Wilshere"
  },
  "74229": {
    "appearances": 814,
    "goals": 57,
    "via": "table",
    "page": "Koke (footballer, born 1992)"
  },
  "74683": {
    "appearances": 721,
    "goals": 32,
    "via": "table",
    "page": "Nemanja Matić"
  },
  "74842": {
    "appearances": 564,
    "goals": 112,
    "via": "table",
    "page": "Mario Götze"
  },
  "77010": {
    "appearances": 382,
    "goals": 104,
    "via": "table",
    "page": "Matthias Sammer"
  },
  "77100": {
    "appearances": 685,
    "goals": 142,
    "via": "table",
    "page": "Lucas Moura"
  },
  "78959": {
    "appearances": 225,
    "goals": 3,
    "via": "table",
    "page": "Martin Kelly (footballer)"
  },
  "79422": {
    "appearances": 554,
    "goals": 0,
    "via": "table",
    "page": "Keylor Navas"
  },
  "85288": {
    "appearances": 601,
    "goals": 111,
    "via": "table",
    "page": "Isco"
  },
  "85314": {
    "appearances": 556,
    "goals": 136,
    "via": "table",
    "page": "Oscar (footballer, born 1991)"
  },
  "87436": {
    "appearances": 751,
    "goals": 198,
    "via": "table",
    "page": "John Barnes"
  },
  "89545": {
    "appearances": 399,
    "goals": 81,
    "via": "table",
    "page": "Zvonimir Boban"
  },
  "91059": {
    "appearances": 454,
    "goals": 110,
    "via": "table",
    "page": "Joshua King (footballer, born 1992)"
  },
  "91919": {
    "appearances": 223,
    "goals": 19,
    "via": "table",
    "page": "Alexi Lalas"
  },
  "91970": {
    "appearances": 590,
    "goals": 58,
    "via": "table",
    "page": "Juan Cuadrado"
  },
  "96182": {
    "appearances": 333,
    "goals": 143,
    "via": "infobox",
    "page": "Preben Elkjær"
  },
  "96342": {
    "appearances": 457,
    "goals": 47,
    "via": "table",
    "page": "Dunga"
  },
  "96754": {
    "appearances": 406,
    "goals": 95,
    "via": "table",
    "page": "Fabio Borini"
  },
  "101091": {
    "appearances": 325,
    "goals": 63,
    "via": "table",
    "page": "Tomas Brolin"
  },
  "101104": {
    "appearances": 461,
    "goals": 0,
    "via": "table",
    "page": "Thomas Ravelli"
  },
  "101126": {
    "appearances": 777,
    "goals": 405,
    "via": "table",
    "page": "Ally McCoist"
  },
  "101317": {
    "appearances": 964,
    "goals": 113,
    "via": "table",
    "page": "Stuart Pearce"
  },
  "101382": {
    "appearances": 733,
    "goals": 146,
    "via": "table",
    "page": "Bryan Robson"
  },
  "101383": {
    "appearances": 1249,
    "goals": 1,
    "via": "table",
    "page": "Peter Shilton"
  },
  "101385": {
    "appearances": 734,
    "goals": 148,
    "via": "table",
    "page": "Chris Waddle"
  },
  "102023": {
    "appearances": 541,
    "goals": 73,
    "via": "table",
    "page": "Dan Petrescu"
  },
  "102030": {
    "appearances": 879,
    "goals": 280,
    "via": "table",
    "page": "Peter Beardsley"
  },
  "102150": {
    "appearances": 409,
    "goals": 137,
    "via": "table",
    "page": "Faustino Asprilla"
  },
  "102200": {
    "appearances": 226,
    "goals": 0,
    "via": "infobox",
    "page": "Sergio Goycochea"
  },
  "102474": {
    "appearances": 445,
    "goals": 29,
    "via": "infobox",
    "page": "Roberto Donadoni"
  },
  "102492": {
    "appearances": 598,
    "goals": 31,
    "via": "table",
    "page": "Paul McGrath (footballer)"
  },
  "102510": {
    "appearances": 373,
    "goals": 13,
    "via": "table",
    "page": "Stig Inge Bjørnebye"
  },
  "102513": {
    "appearances": 514,
    "goals": 48,
    "via": "table",
    "page": "Jorge Campos"
  },
  "102586": {
    "appearances": 561,
    "goals": 107,
    "via": "table",
    "page": "Leonardo Araújo"
  },
  "102590": {
    "appearances": 323,
    "goals": 80,
    "via": "infobox",
    "page": "Branco (footballer)"
  },
  "102704": {
    "appearances": 422,
    "goals": 125,
    "via": "infobox",
    "page": "Dragan Stojković"
  },
  "104637": {
    "appearances": 626,
    "goals": 324,
    "via": "table",
    "page": "Ian Wright"
  },
  "104897": {
    "appearances": 614,
    "goals": 108,
    "via": "table",
    "page": "David Ginola"
  },
  "116155": {
    "appearances": 706,
    "goals": 96,
    "via": "table",
    "page": "Graeme Souness"
  },
  "116679": {
    "appearances": 442,
    "goals": 41,
    "via": "table",
    "page": "Carlo Ancelotti"
  },
  "116754": {
    "appearances": 695,
    "goals": 0,
    "via": "table",
    "page": "Walter Zenga"
  },
  "117193": {
    "appearances": 690,
    "goals": 144,
    "via": "table",
    "page": "Glenn Hoddle"
  },
  "117501": {
    "appearances": 487,
    "goals": 36,
    "via": "infobox",
    "page": "Jean Tigana"
  },
  "117613": {
    "appearances": 730,
    "goals": 171,
    "via": "table",
    "page": "Míchel (footballer, born 1963)"
  },
  "117633": {
    "appearances": 513,
    "goals": 236,
    "via": "table",
    "page": "Sócrates"
  },
  "117996": {
    "appearances": 269,
    "goals": 6,
    "via": "table",
    "page": "Phil Jones (footballer, born 1992)"
  },
  "120627": {
    "appearances": 720,
    "goals": 42,
    "via": "table",
    "page": "Manolo Sanchís"
  },
  "130319": {
    "appearances": 783,
    "goals": 282,
    "via": "table",
    "page": "Trevor Francis"
  },
  "133964": {
    "appearances": 615,
    "goals": 194,
    "via": "table",
    "page": "Lorenzo Insigne"
  },
  "135268": {
    "appearances": 706,
    "goals": 20,
    "via": "table",
    "page": "Alan Hansen"
  },
  "135910": {
    "appearances": 913,
    "goals": 0,
    "via": "table",
    "page": "Neville Southall"
  },
  "140749": {
    "appearances": 715,
    "goals": 363,
    "via": "infobox",
    "page": "John Charles"
  },
  "143424": {
    "appearances": 453,
    "goals": 55,
    "via": "table",
    "page": "Alex Oxlade-Chamberlain"
  },
  "145510": {
    "appearances": 540,
    "goals": 259,
    "via": "infobox",
    "page": "Jairzinho"
  },
  "145988": {
    "appearances": 572,
    "goals": 113,
    "via": "table",
    "page": "Wilfried Zaha"
  },
  "151263": {
    "appearances": 345,
    "goals": 102,
    "via": "table",
    "page": "Garrincha"
  },
  "174867": {
    "appearances": 602,
    "goals": 303,
    "via": "table",
    "page": "Denis Law"
  },
  "174987": {
    "appearances": 358,
    "goals": 0,
    "via": "table",
    "page": "Lev Yashin"
  },
  "176283": {
    "appearances": 510,
    "goals": 22,
    "via": "table",
    "page": "Nobby Stiles"
  },
  "177907": {
    "appearances": 609,
    "goals": 38,
    "via": "table",
    "page": "Harry Maguire"
  },
  "181136": {
    "appearances": 544,
    "goals": 66,
    "via": "table",
    "page": "Piotr Zieliński"
  },
  "193082": {
    "appearances": 547,
    "goals": 65,
    "via": "table",
    "page": "Álex Grimaldo"
  },
  "196086": {
    "appearances": 795,
    "goals": 28,
    "via": "table",
    "page": "Bobby Moore"
  },
  "200631": {
    "appearances": 707,
    "goals": 469,
    "via": "table",
    "page": "Jimmy Greaves"
  },
  "200633": {
    "appearances": 675,
    "goals": 300,
    "via": "table",
    "page": "Geoff Hurst"
  },
  "206040": {
    "appearances": 539,
    "goals": 161,
    "via": "table",
    "page": "Raúl Jiménez"
  },
  "207929": {
    "appearances": 386,
    "goals": 94,
    "via": "table",
    "page": "Dele Alli"
  },
  "212747": {
    "appearances": 814,
    "goals": 121,
    "via": "table",
    "page": "Billy Bremner"
  },
  "212779": {
    "appearances": 803,
    "goals": 80,
    "via": "table",
    "page": "Stanley Matthews"
  },
  "217111": {
    "appearances": 489,
    "goals": 143,
    "via": "table",
    "page": "Hakim Ziyech"
  },
  "229662": {
    "appearances": 762,
    "goals": 64,
    "via": "table",
    "page": "Carlos Alberto Torres"
  },
  "238407": {
    "appearances": 475,
    "goals": 175,
    "via": "table",
    "page": "Alexander Sørloth"
  },
  "255508": {
    "appearances": 566,
    "goals": 143,
    "via": "table",
    "page": "Iñaki Williams"
  },
  "258889": {
    "appearances": 341,
    "goals": 108,
    "via": "table",
    "page": "Dominic Solanke"
  },
  "262396": {
    "appearances": 366,
    "goals": 0,
    "via": "table",
    "page": "Unai Simón"
  },
  "262749": {
    "appearances": 450,
    "goals": 0,
    "via": "table",
    "page": "David Raya"
  },
  "284857": {
    "appearances": 382,
    "goals": 17,
    "via": "table",
    "page": "Marc Cucurella"
  },
  "315779": {
    "appearances": 409,
    "goals": 88,
    "via": "table",
    "page": "Christian Pulisic"
  },
  "325443": {
    "appearances": 396,
    "goals": 195,
    "via": "table",
    "page": "Viktor Gyökeres"
  },
  "332697": {
    "appearances": 344,
    "goals": 32,
    "via": "table",
    "page": "Weston McKennie"
  },
  "357119": {
    "appearances": 307,
    "goals": 13,
    "via": "table",
    "page": "Ibrahima Konaté"
  },
  "357153": {
    "appearances": 306,
    "goals": 0,
    "via": "table",
    "page": "Diogo Costa"
  },
  "364135": {
    "appearances": 306,
    "goals": 82,
    "via": "table",
    "page": "Moise Kean"
  },
  "388198": {
    "appearances": 261,
    "goals": 19,
    "via": "table",
    "page": "Nico Schlotterbeck"
  },
  "392757": {
    "appearances": 283,
    "goals": 14,
    "via": "table",
    "page": "Marc Guéhi"
  },
  "406040": {
    "appearances": 367,
    "goals": 98,
    "via": "table",
    "page": "Ademola Lookman"
  },
  "411295": {
    "appearances": 430,
    "goals": 150,
    "via": "table",
    "page": "Raphinha"
  },
  "420002": {
    "appearances": 370,
    "goals": 135,
    "via": "table",
    "page": "Jean-Philippe Mateta"
  },
  "445939": {
    "appearances": 277,
    "goals": 83,
    "via": "table",
    "page": "Omar Marmoush"
  },
  "451276": {
    "appearances": 370,
    "goals": 93,
    "via": "table",
    "page": "Dominik Szoboszlai"
  },
  "455661": {
    "appearances": 179,
    "goals": 42,
    "via": "table",
    "page": "Nick Woltemade"
  },
  "460939": {
    "appearances": 389,
    "goals": 60,
    "via": "table",
    "page": "Tijjani Reijnders"
  },
  "478573": {
    "appearances": 318,
    "goals": 31,
    "via": "table",
    "page": "Ryan Gravenberch"
  },
  "480267": {
    "appearances": 312,
    "goals": 27,
    "via": "table",
    "page": "Ronald Araújo"
  },
  "486049": {
    "appearances": 262,
    "goals": 40,
    "via": "table",
    "page": "Jérémy Doku"
  },
  "487469": {
    "appearances": 306,
    "goals": 40,
    "via": "table",
    "page": "Vitinha"
  },
  "488362": {
    "appearances": 316,
    "goals": 36,
    "via": "table",
    "page": "Conor Gallagher"
  },
  "495666": {
    "appearances": 299,
    "goals": 9,
    "via": "table",
    "page": "William Saliba"
  },
  "496094": {
    "appearances": 283,
    "goals": 87,
    "via": "table",
    "page": "Karim Adeyemi"
  },
  "502670": {
    "appearances": 311,
    "goals": 80,
    "via": "table",
    "page": "Khvicha Kvaratskhelia"
  },
  "502676": {
    "appearances": 221,
    "goals": 0,
    "via": "table",
    "page": "Giorgi Mamardashvili"
  },
  "502821": {
    "appearances": 163,
    "goals": 9,
    "via": "table",
    "page": "Riccardo Calafiori"
  },
  "503733": {
    "appearances": 250,
    "goals": 47,
    "via": "table",
    "page": "Anthony Gordon (footballer)"
  },
  "503743": {
    "appearances": 239,
    "goals": 50,
    "via": "table",
    "page": "Morgan Rogers"
  },
  "503987": {
    "appearances": 226,
    "goals": 53,
    "via": "table",
    "page": "Noni Madueke"
  },
  "517894": {
    "appearances": 312,
    "goals": 84,
    "via": "table",
    "page": "Matheus Cunha"
  },
  "543499": {
    "appearances": 255,
    "goals": 63,
    "via": "table",
    "page": "Mohammed Kudus"
  },
  "548111": {
    "appearances": 271,
    "goals": 37,
    "via": "table",
    "page": "Álex Baena"
  },
  "553875": {
    "appearances": 309,
    "goals": 29,
    "via": "table",
    "page": "Pedro Porro"
  },
  "557459": {
    "appearances": 196,
    "goals": 14,
    "via": "table",
    "page": "Micky van de Ven"
  },
  "566723": {
    "appearances": 277,
    "goals": 72,
    "via": "table",
    "page": "Michael Olise"
  },
  "567576": {
    "appearances": 181,
    "goals": 16,
    "via": "table",
    "page": "Elliot Anderson"
  },
  "580195": {
    "appearances": 245,
    "goals": 73,
    "via": "table",
    "page": "Jamal Musiala"
  },
  "583255": {
    "appearances": 324,
    "goals": 78,
    "via": "table",
    "page": "Antoine Semenyo"
  },
  "607223": {
    "appearances": 262,
    "goals": 49,
    "via": "table",
    "page": "Rayan Cherki"
  },
  "616341": {
    "appearances": 229,
    "goals": 15,
    "via": "table",
    "page": "Nuno Mendes (footballer, born 2002)"
  },
  "626724": {
    "appearances": 273,
    "goals": 90,
    "via": "table",
    "page": "João Pedro (footballer, born 2001)"
  },
  "627442": {
    "appearances": 248,
    "goals": 104,
    "via": "table",
    "page": "Benjamin Šeško"
  },
  "636703": {
    "appearances": 184,
    "goals": 48,
    "via": "table",
    "page": "Fermín López"
  },
  "670681": {
    "appearances": 188,
    "goals": 18,
    "via": "table",
    "page": "João Neves"
  },
  "687626": {
    "appearances": 247,
    "goals": 18,
    "via": "table",
    "page": "Moisés Caicedo"
  },
  "708265": {
    "appearances": 226,
    "goals": 51,
    "via": "table",
    "page": "Bradley Barcola"
  },
  "709726": {
    "appearances": 196,
    "goals": 67,
    "via": "table",
    "page": "Hugo Ekitike"
  },
  "743591": {
    "appearances": 182,
    "goals": 23,
    "via": "table",
    "page": "Sávio (footballer, born 2004)"
  },
  "744149": {
    "appearances": 154,
    "goals": 5,
    "via": "table",
    "page": "Adam Wharton"
  },
  "776890": {
    "appearances": 218,
    "goals": 66,
    "via": "table",
    "page": "Nicolas Jackson"
  },
  "792380": {
    "appearances": 115,
    "goals": 8,
    "via": "table",
    "page": "Aleksandar Pavlović (footballer)"
  },
  "810092": {
    "appearances": 190,
    "goals": 11,
    "via": "table",
    "page": "Warren Zaïre-Emery"
  },
  "811779": {
    "appearances": 193,
    "goals": 35,
    "via": "table",
    "page": "Alejandro Garnacho"
  },
  "820374": {
    "appearances": 113,
    "goals": 8,
    "via": "table",
    "page": "Kobbie Mainoo"
  },
  "845654": {
    "appearances": 147,
    "goals": 29,
    "via": "table",
    "page": "Kenan Yıldız"
  },
  "861410": {
    "appearances": 170,
    "goals": 28,
    "via": "table",
    "page": "Arda Güler"
  },
  "890290": {
    "appearances": 133,
    "goals": 10,
    "via": "table",
    "page": "Dean Huijsen"
  },
  "890719": {
    "appearances": 70,
    "goals": 12,
    "via": "table",
    "page": "Ethan Nwaneri"
  },
  "890721": {
    "appearances": 85,
    "goals": 1,
    "via": "table",
    "page": "Myles Lewis-Skelly"
  },
  "914562": {
    "appearances": 196,
    "goals": 40,
    "via": "table",
    "page": "Désiré Doué"
  },
  "937958": {
    "appearances": 162,
    "goals": 57,
    "via": "table",
    "page": "Lamine Yamal"
  },
  "948294": {
    "appearances": 142,
    "goals": 33,
    "via": "table",
    "page": "Nico Paz"
  },
  "962110": {
    "appearances": 143,
    "goals": 2,
    "via": "table",
    "page": "Pau Cubarsí"
  },
  "971570": {
    "appearances": 144,
    "goals": 34,
    "via": "table",
    "page": "Endrick"
  },
  "1056993": {
    "appearances": 125,
    "goals": 35,
    "via": "table",
    "page": "Estêvão Willian"
  }
}
