// Auto-generated by scripts/fetchWikiCareerStats.ts — do not edit by hand.
// Club career totals from English Wikipedia for icons whose Transfermarkt
// stats are missing or a stub (under 50 appearances).

export const wikiCareerStats: Record<
  string,
  { appearances: number; goals: number; via: 'table' | 'infobox'; page: string }
> = {
  "3830": {
    "appearances": 468,
    "goals": 110,
    "via": "table",
    "page": "Paul Gascoigne"
  },
  "7940": {
    "appearances": 685,
    "goals": 238,
    "via": "table",
    "page": "Ronald Koeman"
  },
  "10201": {
    "appearances": 338,
    "goals": 105,
    "via": "infobox",
    "page": "Rivellino"
  },
  "17121": {
    "appearances": 647,
    "goals": 606,
    "via": "infobox",
    "page": "Pelé"
  },
  "18944": {
    "appearances": 667,
    "goals": 57,
    "via": "table",
    "page": "Gerard Piqué"
  },
  "22068": {
    "appearances": 715,
    "goals": 161,
    "via": "table",
    "page": "Franck Ribéry"
  },
  "35518": {
    "appearances": 784,
    "goals": 125,
    "via": "table",
    "page": "David Silva"
  },
  "65230": {
    "appearances": 863,
    "goals": 21,
    "via": "table",
    "page": "Sergio Busquets"
  },
  "68290": {
    "appearances": 643,
    "goals": 379,
    "via": "table",
    "page": "Neymar"
  },
  "117633": {
    "appearances": 513,
    "goals": 236,
    "via": "table",
    "page": "Sócrates"
  },
  "145510": {
    "appearances": 540,
    "goals": 259,
    "via": "infobox",
    "page": "Jairzinho"
  },
  "151263": {
    "appearances": 345,
    "goals": 102,
    "via": "table",
    "page": "Garrincha"
  },
  "174867": {
    "appearances": 602,
    "goals": 303,
    "via": "table",
    "page": "Denis Law"
  },
  "174987": {
    "appearances": 358,
    "goals": 0,
    "via": "table",
    "page": "Lev Yashin"
  },
  "196086": {
    "appearances": 795,
    "goals": 28,
    "via": "table",
    "page": "Bobby Moore"
  },
  "200631": {
    "appearances": 707,
    "goals": 469,
    "via": "table",
    "page": "Jimmy Greaves"
  },
  "200633": {
    "appearances": 675,
    "goals": 300,
    "via": "table",
    "page": "Geoff Hurst"
  },
  "212779": {
    "appearances": 803,
    "goals": 80,
    "via": "table",
    "page": "Stanley Matthews"
  },
  "229662": {
    "appearances": 762,
    "goals": 64,
    "via": "table",
    "page": "Carlos Alberto Torres"
  },
  "937958": {
    "appearances": 162,
    "goals": 57,
    "via": "table",
    "page": "Lamine Yamal"
  }
}
