import { hashSeed, mulberry32, shuffle } from '@/lib/seeded'
import { tenableQuestions as rawQuestions } from './questions'
import enrichment from './enrichment.json'
import { withOpenMembers } from './openSets'
import type { TenableGroup, TenableQuestion } from './types'

export type {
  TenableAnswer,
  TenableGroup,
  TenableDifficulty,
  TenableKind,
  TenableQuestion,
} from './types'

/**
 * Curated bank, with open categories completed from `openSets.json`
 * (`npm run tenable:open`) and portraits merged in. `enrichment.json` is
 * generated by `npm run tenable:verify` - never hand-edited - keeping
 * questions.ts authoring clean. Missing enrichment just means no image (a name
 * chip renders instead).
 */
const enrichmentMap = enrichment as Record<string, { id?: string; image?: string }>

export const tenableQuestions: TenableQuestion[] = withOpenMembers(rawQuestions).map((q) => ({
  ...q,
  answers: q.answers.map((a) => {
    const extra = enrichmentMap[`${q.id}#${a.rank}`]
    return extra ? { ...a, id: a.id ?? extra.id, image: a.image ?? extra.image } : a
  }),
}))

export function getTenableQuestionById(id: string): TenableQuestion | undefined {
  return tenableQuestions.find((q) => q.id === id)
}

// Lives in its own module so the board can use it without bundling the question bank.
export { tenableTarget } from '@/lib/tenable/target'

/**
 * Deterministically pick `count` questions for a session. Same seed + filters →
 * same set (so a puzzle is stable/shareable, mirroring the bingo board seed).
 */
export function selectTenableQuestions(
  seed: string,
  count: number,
  opts?: {
    groups?: TenableGroup[]
    difficulty?: TenableQuestion['difficulty'] | 'mixed'
    /** Picked from the setup gallery - overrides count and filters. */
    selectedId?: string
  },
): TenableQuestion[] {
  if (opts?.selectedId) {
    const picked = getTenableQuestionById(opts.selectedId)
    if (picked) return [picked]
  }
  const groups = opts?.groups
  const difficulty = opts?.difficulty
  const pool = tenableQuestions.filter((q) => {
    if (groups && groups.length && !groups.includes(q.group)) return false
    if (difficulty && difficulty !== 'mixed' && q.difficulty !== difficulty) return false
    return true
  })
  const rand = mulberry32(hashSeed(seed))
  return shuffle(pool, rand).slice(0, count)
}
