/**
 * Writes small generated modules derived from the player list, so client code
 * never has to import the multi-MB src/data/players.ts just to compute them:
 *
 *   src/data/categoryLabels.generated.ts   — "traits" / "managers" bingo axes
 *   src/data/playerFameScores.generated.ts — every player's fameScore (desc)
 *
 * Called by writePlayers.ts; can also be run standalone against the current
 * src/data/players.ts: npm run write-derived
 */
import * as fs from 'fs'
import * as path from 'path'
import type { Player } from '../src/types/player'

const DATA_DIR = path.join(__dirname, '..', 'src', 'data')
const LABELS_FILE = path.join(DATA_DIR, 'categoryLabels.generated.ts')
const FAME_FILE = path.join(DATA_DIR, 'playerFameScores.generated.ts')

/** Only surface labels at least this many players have, so no square is unwinnable. */
export const MIN_PER_CATEGORY = 8

function labelsWithMinCount(
  players: Player[],
  selector: (p: Player) => string[] | undefined,
  min: number,
): string[] {
  const counts = new Map<string, number>()
  for (const p of players) {
    for (const label of selector(p) ?? []) {
      counts.set(label, (counts.get(label) ?? 0) + 1)
    }
  }
  return [...counts.entries()]
    .filter(([, n]) => n >= min)
    .sort((a, b) => b[1] - a[1])
    .map(([label]) => label)
}

const HEADER = '// Auto-generated by scripts/writeDerivedPlayerData.ts - do not edit by hand.'
const FOOTER = '// Regenerated by "npm run write-players" (or "npm run write-derived").'

function writeCategoryLabels(players: Player[]) {
  const traits = labelsWithMinCount(players, (p) => p.tags, MIN_PER_CATEGORY)
  const managers = labelsWithMinCount(players, (p) => p.managers, MIN_PER_CATEGORY)

  fs.writeFileSync(
    LABELS_FILE,
    `${HEADER}
// Labels held by >= ${MIN_PER_CATEGORY} of ${players.length} players, sorted by player count (desc).
${FOOTER}

export const traits: string[] = ${JSON.stringify(traits)}

export const managers: string[] = ${JSON.stringify(managers)}
`,
  )
  console.log(`✓ Wrote ${traits.length} traits, ${managers.length} managers to ${LABELS_FILE}`)
}

function writeFameScores(players: Player[]) {
  const scores = players.map((p) => p.fameScore ?? 0).sort((a, b) => b - a)

  fs.writeFileSync(
    FAME_FILE,
    `${HEADER}
// fameScore of all ${players.length} players, sorted desc — lets the setup screen count
// players above a fame threshold without bundling players.ts.
${FOOTER}

export const playerFameScores: number[] = ${JSON.stringify(scores)}
`,
  )
  console.log(`✓ Wrote ${scores.length} fame scores to ${FAME_FILE}`)
}

export function writeDerivedPlayerData(players: Player[]) {
  writeCategoryLabels(players)
  writeFameScores(players)
}

if (require.main === module) {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { enrichedFootballPlayers } = require('../src/data/players')
  writeDerivedPlayerData(enrichedFootballPlayers)
}
